version: '3'

services:
  backend:
    build: ./django
    restart: always
    container_name: django
    ports:
      - '8000:8000'
    depends_on:
      - db
    environment:
      POSTGRES_HOST: db
      POSTGRES_USER: root
      POSTGRES_PORT: 5432
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres

  db:
    image: postgres
    restart: always
    container_name: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: root
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
