version: '3'

services:
  backend:
    build: ./django
    restart: always
    container_name: django
    ports:
      - '8000:8000'
    depends_on:
      - db
    env_file:
      - env/django.env

  db:
    image: postgres
    restart: always
    container_name: postgres
    ports:
      - '5432:5432'
    env_file:
      - env/postgres.env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus/:/etc/prometheus/
    ports:
      - '9090:9090'

  grafana:
    image: grafana/grafana:8.5.3-ubuntu
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
      - grafana-configs:/etc/grafana

volumes:
  postgres_data:
  grafana-data:
  grafana-configs:
